name: yartu_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Visual Elements
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  flutter_svg: ^1.0.3
  animate_do: ^2.1.0
  shimmer_animation: ^2.1.0+1

  # Api Connection
  dio: ^4.0.4
  connectivity_plus: ^2.2.0

  # State Management
  provider: ^6.0.2

  # Json Operations
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  build_runner: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  device_preview: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # Default Font
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope.ttf

  # Other Font
    - family: AvenirNext
      fonts:
        - asset: assets/fonts/Avenir-Next.otf
